bucket_name           = "travelease-website-bucket"
lambda_function_name  = "travelease-contact-form"
dynamodb_table_name   = "travelease-submissions"
verified_email        = "shangeeth023@gmail.com"
region                = "ca-central-1"